### PR TITLE
Add new "build-asl3" script

### LINKED ISSUE #387: Issue building with ASL3 Pi image
Greetings, 

I was hoping to do some debug and possibly fix an issue I ran into with app_rpt, but I an running into an issue building app_rpt. 

The host is a Pi4 with 8 GB ram, running the ASL3 image. 

I followed the steps as outlined here: 
https://github.com/AllStarLink/app_rpt/blob/master/README.md

I did add the "-u asterisk" to the phreaknet arguments: 

```phreaknet install -d -b -v 20 -u asterisk```

```
DAHDI already present but install not forced, skipping...
Proceeding to install Asterisk 20 (~major 20)...
asterisk-20-current.tar.gz  100%[========================================>]  26.98M  9.54MB/s    in 2.8s
Asterisk MMmmPP: 200902
Installing production version asterisk-20.9.2...
```
I got through the "phreaknet" script, with the only additional step being to install git prior to running it, not a big deal. 

However, when I run rpt_install.sh, I received the following errors: 
```
root@simplex900:/usr/src# ./rpt_install.sh
Already up to date.
Updating ourself
Already up to date.
Script is now the latest version
asterisk-20.9.2/
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libusb-dev is already the newest version (2:0.1.12-32).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
... additional adding modules...
Adding module utils/pi-tune-menu.c
Adding module utils/radio-tune-menu.c
Adding module utils/simpleusb-tune-menu.c
4
CC="cc" CXX="g++" LD="" AR="" RANLIB="" CFLAGS="" LDFLAGS="" make -C menuselect CONFIGURE_SILENT="--silent" makeopts
make[1]: Entering directory '/usr/src/asterisk-20.9.2/menuselect'
make[1]: 'makeopts' is up to date.
make[1]: Leaving directory '/usr/src/asterisk-20.9.2/menuselect'
Generating input for menuselect ...

***********************************************************
  The existing menuselect.makeopts file did not specify
  that 'app_rpt' should not be included.  However,
dependencies for this module were not found.

  Either run 'make menuselect' or remove the existing
  menuselect.makeopts file to resolve this issue.
***********************************************************
```

I attempted to follow the directions in the message, running ```make menuselect``` in the asterisk directory, but oddly, the same error results as above. If I remove the menuselect.makeopts file, then I can run ```make menuselect```, however, it does not allow me to select app_rpt (it is labeled with "XXX"). I believe this is due to some dependency being missing. The dependencies are listed for the module as:

```Depends on: tonezone(E), res_curl(M), curl(E), dahdi(E)```

The module res_curl is already selected. I am unsure how to satisfy the other dependencies. But I digress, I suspect the patch steps are intended to remedy the build issue. 

If someone can guide me in to getting this built, it would be much appreciated. I have a few bugs I'd like to trace out and having a working build system would help tremendously. 

Thanks, 

--E
de W6EL

### PR DESCRIPTION
**Pull request by Allan-N**
Usage : build-asl3 -a ASTV -v RPTV [-r RELV] [-d DESTDIR] [-l] ACTIONS

Required options :
  -a  Asterisk version    (e.g. 20.9.2)
  -v  ASL/app_rpt version (e.g. 3.0.4)

Optional options :
  -r  Release version         (default: 1)
  -d  local install directory (default: "/")
  -l  Create merged source directory with symlinks

Actions (specify one or more) :
  source  - create the merged source directory
  clean   - "clean" the merged source directory
  build   - "build" the source code
  install - "install" the build results, locally
  package - create Debian packages

Note: specifying "build", "install", or "package" will, if needed, create the merged source directory.

Note: you can use the "AST_VER", "RPT_VER", and "REL_VER" environment variables
to specify the Asterisk, ASL/app_rpt, and Release versions.

### CODE REVIEW

**Comment by Allan-N** [comment]
Still needs a man page.
Need to test on x86
Need to review whether (and when) to remove no-longer-used bits

**Review by jxmx — APPROVED** [review]

**Comment by davidgsd** [comment]
I can successfully build everything on amd64 by running "asl3-asterisk/build-tree -a 20.9.2 -v 3.0.4 -r 2", and "asl3-asterisk/build-asl3 -a 20.9.2 -v 3.0.4 -r 2 build" seemed to take almost as long initially. "asl3-asterisk/build-asl3 -a ... install" completed quickly.  "build-asl3 ... build install" then ran faster the next time, taking only about 5 minutes. 

However, the changes I made in ./app_rpt/ did **not** get brought in.  So it then appeared that maybe build-asl3 was pulling from asl3-asterisk-20.9.2+asl3-3.0.4/ instead of app_rpt/ (as build-tree does), as I see that files were indeed compiled there. So I copied my changed files to asl3-asterisk-20.9.2+asl3-3.0.4/ then ran the build again, but still no change.  I then saw that although I had copied a .c file into this dir, that the .o and .so were not updated during the build. So I then deleted the .o and .so associated with my changed .c file, thinking the make process would notice that and actually make the file, but it did not.

So I then tried "build-asl3...clean" but it gives the below error message:
dh_clean: error: mv debian/.debhelper/bucket/files/81564062cef83cd011f09237c9073926da3781d8342bb63dd67bd1fd923ed71f.tmp third-party/pjproject/source/config.guess: No such file or directory

after running "build-asl3...source" the ...clean option then worked, but it only cleaned certain dirs but not most other ie. channels/. I then cd'd into asl-asterisk and ran make clean, which then did clean all remaining dirs, so now I'm building the whole thing again. 

Do you have any suggestions on how to get the script to use the files in app-rpt/ instead of 
asl3-asterisk-xxx+asl3-xxx/? And of course if the script could be optimized to actually detect what .c file(s) changed and only rebuild those that would be great. As it is now it seems to build the stock Ast+app-rpt only while not giving an opportunity to change files and not seeing when any .c files did change. Maybe that's what this script is supposed to do, but in that case the question is how can I change one .c file and quickly build and install app-rpt without going through the 30+ minute build-tree process every time. Thanks

**Comment by Allan-N** [comment]
I added a "man" page to this branch that should help explain things a bit.  That page includes some information on how everything fits together and what actions you need to take for iterative development.

**Comment by davidgsd** [comment]
New script is working well. After changing 1 c file and rebuilding it took only 4 mins. (on a 3040 thin-client w/quad-core Atom 1.4GHz processor). Will do some further testing today.

**Comment by davidgsd** [comment]
Things are working nicely now. I can go into the combined source folder (asl3-asterisk-x.x.x+asl3-x.x.x), change 1 .c file, do a 'make' and then 'make install' there, and it then recompiles just the one file and updates the asterisk+asl install, all within a couple minutes.

**Pull request merged**
